import{a as c,i}from"./assets/vendor-vZoX7XBu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const u="50344127-726c85bb6f98eba42715a8612",d=async s=>{try{return(await c.get("https://pixabay.com/api/",{params:{key:u,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true"}})).data.hits}catch(r){return console.error("Error fetching images:",r),[]}},m=s=>{const r=document.querySelector(".gallery"),n=s.map(o=>`
                <li class="gallery-item">
                    <a href="${o.largeImageURL}" class="gallery-link">
                        <img src="${o.webformatURL}" alt="${o.tags}" class="gallery-image" />
                    </a>
                    <div class="image-info">
                        <p><b>Likes:</b> ${o.likes} | <b>Views:</b> ${o.views} | <b>Comments:</b> ${o.comments} | <b>Downloads:</b> ${o.downloads}</p>
                    </div>
                </li>
            `).join("");r.insertAdjacentHTML("beforeend",n)},y=()=>{document.querySelector(".gallery").innerHTML=""},f=()=>{document.getElementById("loader").style.display="block"},p=()=>{document.getElementById("loader").style.display="none"},l=document.querySelector(".form"),g=l.querySelector('input[name="search-text"]');l.addEventListener("submit",async s=>{s.preventDefault();const r=g.value.trim();if(!r){i.error({title:"Error",message:"Please enter a search term."});return}f(),y();const n=await d(r);n.length===0?i.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"}):m(n),p()});
//# sourceMappingURL=index.js.map
